modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/travel-bag/issues" #optional
[[mods]] #mandatory
modId="travel_bag" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Travel Bag" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Corail31/trash/master/update_travel_bag.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/travel-bag" #optional
#logoFile="examplemod.png" #optional
credits="Special Thanks to fml and forge guys" #optional
authors="Corail31" #optional
description='''
Provides somes items "Travel bags" to store your items in, with some behaviors with some mods (Tombstone/Curios)
'''
[[dependencies.travel_bag]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30.0.19,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.travel_bag]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1,1.16)"
    ordering="NONE"
    side="BOTH"
